In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/kaggle/input/datasets/nikhilsingh4356/pokemon-dataset/pokemon.csv")

In [4]:
df.head()

,index_name,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total_power
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,98
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,125
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,165
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,223
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,95

In [5]:
df.columns.tolist()

['index_name',
 'Name',
 'Type 1',
 'Type 2',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary',
 'total_power']

In [6]:
unique_pokemon = df["Name"].nunique()
print("Uniques Pokemons",unique_pokemon )

Uniques Pokemons 799

In [7]:
duplicate_names = df['Name'].value_counts()
print(duplicate_names[duplicate_names > 1])

Series([], Name: count, dtype: int64)

In [9]:
top_5_attack = df.nlargest(5,'Attack')[['Name','Type 1','Attack','Defense']]

In [10]:
print(top_5_attack)

                   Name   Type 1  Attack  Defense
163       Mega Mewtwo X  Psychic     190      100
232      Mega Heracross      Bug     185      115
424      Primal Groudon   Ground     180      160
426       Mega Rayquaza   Dragon     180      100
429  DeoxysAttack Forme  Psychic     180       20

In [15]:
highest_hp = df.nlargest(1,"HP")[["Name","HP"]]
print(highest_hp)

        Name   HP
261  Blissey  255

In [16]:
average_hp = df["HP"].mean()
print(average_hp)

69.25875

In [18]:
df.groupby("Type 1")['index_name'].count()

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: index_name, dtype: int64

In [22]:
avg_attack=df.groupby("Type 1")['Attack'].mean()
print(avg_attack)

Type 1
Bug          70.971014
Dark         88.387097
Dragon      112.125000
Electric     69.090909
Fairy        61.529412
Fighting     96.777778
Fire         84.769231
Flying       78.750000
Ghost        73.781250
Grass        73.214286
Ground       95.750000
Ice          72.750000
Normal       73.469388
Poison       74.678571
Psychic      71.456140
Rock         92.863636
Steel        92.703704
Water        74.151786
Name: Attack, dtype: float64

In [25]:
avg_attack.max()

112.125

In [27]:
df["Total Stats"] = df["HP"]+df["Attack"]+df["Defense"]+df["Sp. Atk"]+df["Sp. Def"]

In [32]:
df.nlargest(10,"Total Stats")[["Name","Total Stats"]]

                    Name  Total Stats
422        Primal Kyogre          680
424       Primal Groudon          680
426        Mega Rayquaza          665
163        Mega Mewtwo X          650
164        Mega Mewtwo Y          640
268       Mega Tyranitar          629
494        Mega Garchomp          608
711  Kyurem Black Kyurem          605
712  Kyurem White Kyurem          605
552               Arceus          600

In [44]:
Attackgt100 = len(df[df["Attack"]>100])
print(Attackgt100)

defenselt50 = len(df[df["Defense"]<50])
print(defenselt50)

speedmt80 = len(df[df["Speed"]>80])
print(speedmt80)

170
163
263

In [53]:
df

,index_name,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total_power,Total Stats
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,True,98,273
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,True,125,345
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,True,165,445
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,True,223,545
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,True,95,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,250,550
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,270,590
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,170,530
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,220,600
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,230,530

In [56]:
filtered = df[(df["Legendary"] == True)&
(df["Generation"] ==1 )&
(df["Type 1"] == "Water")
]

In [57]:
filtered

,index_name,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total_power,Total Stats
9,10,Squirtle,Water,NaN,44,48,65,50,64,43,1,True,113,271
10,11,Wartortle,Water,NaN,59,63,80,65,80,58,1,True,143,347
11,12,Blastoise,Water,NaN,79,83,100,85,105,78,1,True,183,452
12,13,Mega Blastoise,Water,NaN,79,103,120,135,115,78,1,True,223,552
59,60,Psyduck,Water,NaN,50,52,48,65,50,55,1,True,100,265
60,61,Golduck,Water,NaN,80,82,78,95,80,85,1,True,160,415
65,66,Poliwag,Water,NaN,40,50,40,40,40,90,1,True,90,210
66,67,Poliwhirl,Water,NaN,65,65,65,50,50,90,1,True,130,295
67,68,Poliwrath,Water,Fighting,90,95,95,70,90,70,1,True,190,440
78,79,Tentacool,Water,Poison,40,40,35,50,100,70,1,True,75,265
79,80,Tentacruel,Water,Poison,80,70,65,80,120,100,1,True,135,415
85,86,Slowpoke,Water,Psychic,90,65,65,40,40,15,1,True,130,300
86,87,Slowbro,Water,Psychic,95,75,110,100,80,30,1,True,185,460
87,88,Mega Slowbro,Water,Psychic,95,75,180,130,80,30,1,True,255,560
93,94,Seel,Water,NaN,65,45,55,45,70,45,1,True,100,280
94,95,Dewgong,Water,Ice,90,70,80,70,95,70,1,True,150,405
97,98,Shellder,Water,NaN,30,65,100,45,25,40,1,True,165,265
98,99,Cloyster,Water,Ice,50,95,180,85,45,70,1,True,275,455
106,107,Krabby,Water,NaN,30,105,90,25,25,50,1,True,195,275
107,108,Kingler,Water,NaN,55,130,115,50,50,75,1,True,245,400
125,126,Horsea,Water,NaN,30,40,70,70,25,60,1,True,110,235
126,127,Seadra,Water,NaN,55,65,95,95,45,85,1,True,160,355
127,128,Goldeen,Water,NaN,45,67,60,35,50,63,1,True,127,257
128,129,Seaking,Water,NaN,80,92,65,65,80,68,1,True,157,382
129,130,Staryu,Water,NaN,30,45,55,70,55,85,1,True,100,255
130,131,Starmie,Water,Psychic,60,75,85,100,85,115,1,True,160,405
139,140,Magikarp,Water,NaN,20,10,55,15,20,80,1,True,65,120
140,141,Gyarados,Water,Flying,95,125,79,60,100,81,1,True,204,459
141,142,Mega Gyarados,Water,Dark,95,155,109,70,130,81,1,True,264,559
142,143,Lapras,Water,Ice,130,85,80,85,95,60,1,True,165,475
145,146,Vaporeon,Water,NaN,130,65,60,110,95,65,1,True,125,460

In [61]:
def speed_category(speed):
    if speed<=40:
        return "Slow"
    if speed > 40 & speed <=80:
        return "Medium"
    if speed > 80:
        return "Fast"
df["Speed_Category"] = df["Speed"].apply(speed_category) 

difrentiation = df["Speed_Category"].value_counts()
print(difrentiation)

Speed_Category
Medium    641
Slow      159
Name: count, dtype: int64

In [62]:
df["Attack-to-Defense-Ratio"] = df["Attack"]/df["Defense"]

In [67]:
maxrat = df["Attack-to-Defense-Ratio"].max()
minrat = df["Attack-to-Defense-Ratio"].min()
avgrat = df["Attack-to-Defense-Ratio"].mean()

In [69]:
print("Maximum ration",maxrat)
print("Minimum ration",minrat)
print("Average ration",avgrat)

Maximum ration 9.0
Minimum ration 0.043478260869565216
Average ration 1.1645466088751797

In [70]:
df

,index_name,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,total_power,Total Stats,Speed_Category,Attack-to-Defense-Ratio
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,True,98,273,Medium,1.000000
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,True,125,345,Medium,0.984127
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,True,165,445,Medium,0.987952
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,True,223,545,Medium,0.813008
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,1,True,95,244,Medium,1.209302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,250,550,Medium,0.666667
796,797,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,270,590,Medium,1.454545
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,170,530,Medium,1.833333
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,220,600,Medium,2.666667
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,230,530,Medium,0.916667

In [80]:
total_pokemon = len(df)
total_legendary = len(df["Legendary"] == True)
avg_gen = df.groupby("Generation")[["HP", "Attack", "Defense", "Speed"]].mean()
most_com_type = df["Type 1"].value_counts().max()
best_gen = df.groupby("Generation")[["Total Stats"]].mean().max()


print("=" * 50)
print("POKEMON DATASET SUMMARY REPORT")
print("=" * 50)
print(f"\nTotal Pokemon: {total_pokemon}")
print(f"Legendary Pokemon: {total_legendary}")
print(f"\nAverage Stats by Generation:\n{avg_gen}")
print(f"\nMost Common Type: {most_com_type}")
print(f"Generation with Highest Avg Total Stats: {best_gen}")
print("\n" + "=" * 50)

==================================================
POKEMON DATASET SUMMARY REPORT
==================================================

Total Pokemon: 800
Legendary Pokemon: 800

Average Stats by Generation:
                   HP     Attack    Defense      Speed
Generation
1           65.819277  76.638554  70.861446  72.584337
2           71.207547  72.028302  73.386792  61.811321
3           66.543750  81.625000  74.100000  66.925000
4           73.082645  82.867769  78.132231  71.338843
5           71.787879  82.066667  72.327273  68.078788
6           68.268293  75.804878  76.682927  66.439024

Most Common Type: 112
Generation with Highest Avg Total Stats: Total Stats    387.677686
dtype: float64

==================================================